:toc:
:doctype: book
:icons: font
:icon-set: font-awesome
:source-highlighter: highlightjs
:toclevels: 4
:sectlinks:
:author: "mon0mon"
:hardbreaks:

== 6.8 매개변수 객체 만들기 (Introduce Parameter Object)

[open]
.리팩토링 이전
--
[source,kotlin]
----
class UnnamedClass {
    fun amountInvoiced(startDate: LocalDate, endDate: LocalDate) {}
    fun amountReceived(startDate: LocalDate, endDate: LocalDate) {}
    fun amountOverdue(startDate: LocalDate, endDate: LocalDate) {}
}
----
--

[open]
.리팩토링 이후
--
[source,kotlin]
----
class UnnamedClass {
    fun amountInvoiced(aDateRange: DateRange) {}
    fun amountReceived(aDateRange: DateRange) {}
    fun amountOverdue(aDateRange: DateRange) {}
}

data class DateRange(
    val startDate: LocalDate,
    val endDate: LocalDate
)
----
--

### 배경

데이터 뭉치를 데이터 구조로 묶을 경우, 데이터 간의 관계가 명확해짐
또한 매개변수의 수가 줄어들며, 같은 데이터 구조를 사용하는 함수에서는 일관성도 높여줌

이 리팩터링은 코드를 더 근본적으로 변경할 수 있음
데이터 구조에 담길 데이터에에 공통적으로 적용되는 동작을 추출하여 함수로 만들 수 있음
이 과정에서 새로 만든 데이터 구조가 문제 영역을 훨씬 간결하게 표현하는 추상 개념으로 격상되며, 코드의 개념을 다시 그릴 수도 있음


### 절차

. 적당한 데이터 구조가 없다면, 새로 만든다
* 데이터 구조를 값 객체 (Value Object)로 만드는 것을 권장
. 테스트
. 함수 선언 바꾸기^6.5절^로 새 데이터 구조를 매개변수로 추가
. 테스트
. 함수 호출 시 새로운 데이터 구조 인스턴스를 넘기도록 수정
* 수정 시마다 테스트
. 기존 매개변수를 사용하던 코드를 새 데이터 구조의 원소를 사용하도록 변경
. 변경이 완료되면, 기존 매개변수를 제거하고 테스트


[#_예시]
### 예시

[open]
.리팩터링 전
--
[source,kotlin]
----
fun readingsOutsideRange(station: Station, min: Int, max: Int): List<TemperatureData> {
return station.readings.filter { r -> r.temp < min || r.temp > max }
}

@Serializable
data class Station(
    val name: String,
    val readings: List<TemperatureData>
)

@Serializable
data class TemperatureData (
    val temp: Int,
    @Contextual
    val time: LocalDateTime
)
----
--

[open]
.리팩터링 후
--
[source,kotlin]
----
fun readingsOutsideRange(station: Station, numberRange: NumberRange): List<TemperatureData> {
    return station.readings.filter { r -> r.temp < numberRange.min || r.temp > numberRange.max }
}

data class NumberRange(
    val min: Int,
    val max: Int
)
----
--

. 묶은 데이터를 표현하는 클래스 선언
. 새로 만든 객체를 readingsOutsideRange() 매개변수로 추가하도록 함수 선언 변경
. 테스트
. 온도 범위를 객체 형태로 전달하도록, 호출문을 변경
. 기존 매개변수를 사용하는 부분을 변경
. 테스트

#### 진정한 값 객체로 거듭나기

[open]
.리팩터링 후
--
[source,kotlin]
----
fun readingsOutsideRange(station: Station, numberRange: NumberRange): List<TemperatureData> {
    return station.readings.filter { r -> !numberRange.contains(r.temp) }
}

data class NumberRange(
    val min: Int,
    val max: Int
) {
    fun contains(value: Int): Boolean = (value >= this.min) && (value <= this.max)
}
----
--

매개변수 그룹을 객체로 교차 후에는 관련 동작을 클래스에 위치할 수 있음
예시에서는 온도가 허용 범위 안에 있는지 검사하는 메서드를 클래스에 추가
다른 유용한 동작도 범위 클래스로 옮겨서, 코드 베이스 전반을 간소화할 수 있음
진정한 값 객체에서는 값을 기반으로 한 동치성 검사 메서드(equality method)가 존재해야함
