:toc:
:doctype: book
:icons: font
:icon-set: font-awesome
:source-highlighter: highlightjs
:toclevels: 4
:sectlinks:
:author: "mon0mon"
:hardbreaks:

== 6.9 여러 함수를 클래스로 묶기 (Combine Functions into Class)

[open]
.리팩토링 이전
--
[source,kotlin]
----
fun base() {}
fun taxableCharge() {}
fun calculateBaseCharge() {}
----
--

[open]
.리팩토링 이후
--
[source,kotlin]
----
class Reading {
    fun base() {}
    fun taxableCharge() {}
    fun calculateBaseCharge() {}
}
----
--

### 배경

클래스는 대다수의 최신 프로그래밍 언어가 제공하는 기본적인 빌딩 블록
데이터와 함수를 하나의 공유 환경으로 묶은 후, 일부를 외부에 제공

공통 데이터를 중심으로 긴밀하게 엮여 작동하는 함수 무리는 클래스로 묶기

.클래스의 장점
. 클래스는 이 함수들이 공유하는 공통 환경을 명확히 표현
. 각 함수에 전달되는 인수를 줄여 함수 호출을 간결하게 할 수 있음

이 리팩터링은 이미 만들어진 함수를 재구성 또는 새 클래스의 메서드로 뽑아내는 데에도 좋음

함수를 한데 묶는 또 다른 방법으로는 여러 함수를 변환 함수로 묶기^6.10절^이 있음
어떤 방식으로 진행될 지는 프로그램의 문맥을 살펴보고 정해야 함

클래스를 지원하지 않는 언어를 사용할 때는 같은 기능을 link:https://martinfowler.com/bliki/FunctionAsObject.html['함수를 객체처럼'(Function As Object) 패턴]을 이용해 구현


### 절차

. 함수들이 공유하는 공통 데이터 레코드를 캡슐화^7.1절^
* 공통 데이터가 레코드 구조로 묶여 있지 않다면, 먼저 매개변수 객체 만들기 ^6.8절^로 데이터를 하나로 묶는 레코드를 만들기
. 공통 레코드를 사용하느 함수 각각을 새 클래스로 옮긴다(함수 옮기기^8.1절^)
* 공통 레코드의 멤버는 함수 호출문의 인수 목록에서 제거
. 데이터를 조작하는 로직들을 함수로 추출^6.1절^해서 새 클래스로 옮기기


[#_예시]
### 예시

[open]
.리팩터링 전
--
[source,kotlin]
----
val readingJson: String = """
{
    customer: "ivan",
    quantity: 10,
    month: 5,
    year: 2017
}
"""

fun acquireReading() = json.decodeFromString(Reading.serializer(), readingJson)
fun baseRate(month: Int, year: Int): Double = TODO("Not Implemented")
fun taxThreshold(year: Int): Double = TODO("Not Implemented")

val aReading = acquireReading()
val base = baseRate(month = aReading.month, year = aReading.year) * aReading.quantity
val texableCharge = 0.0.coerceAtMost(base - taxThreshold(aReading.year))

fun calculateBaseCharge(aReading: Reading): Double =
    baseRate(month = aReading.month, year = aReading.year) * aReading.quantity

@Serializable
data class Reading(
    val customer: String,
    val quantity: Int,
    val month: Int,
    val year: Int
)
----
--

[open]
.리팩터링 후
--
[source,kotlin]
----
fun baseRate(month: Int, year: Int): Double = TODO("Not Implemented")
fun taxThreshold(year: Int): Double = TODO("Not Implemented")

@Serializable
data class Reading(
    val customer: String,
    val quantity: Int,
    val month: Int,
    val year: Int
) {
    fun baseCharge(): Double = baseRate(month = this.month, year = this.year) * this.quantity
    val texableCharge
        get() = 0.0.coerceAtMost(this.baseCharge() - taxThreshold(this.year))
}
----
--

. 레코드를 클래스로 변환하기 위해 레코드를 캡슐화하기^7.1절^
. 이미 만들어져 있는 calculateBaseCharge()를 옮기기
* 함수 옮기기^8.1절^
* 함수 이름 바꾸기^6.5절^
. 세금을 부과할 소비량을 계산하는 코드를 함수로 추출^6.1절^
. 추출한 함수를 Reading 클래스로 옮기기 (함수 옮기기^8.1절^)

프로그램의 다른 부분에서 데이터를 갱신할 가능성이 꽤 있을 때는 클래스로 묶어두면 도움이 된다
