:toc:
:doctype: book
:icons: font
:icon-set: font-awesome
:source-highlighter: highlightjs
:toclevels: 4
:sectlinks:
:author: "mon0mon"
:hardbreaks:

== 7.4 임시 변수를 질의 함수로 바꾸기 (Replace Temp with Query)

[open]
.리팩토링 이전
--
[source,kotlin]
----
data class Item (
    val price: Int
)

data class Order(
    val quantity: Int,
    val item: Item
) {
    val price: Double
        get() {
            val basePrice = quantity * item.price
            val discountFactor = if (basePrice > 1000) 0.95 else 0.98

            return basePrice * discountFactor
        }
}
----
--

[open]
.리팩토링 이후
--
[source,kotlin]
----
data class Item (
    val price: Int
)

data class Order(
    val quantity: Int,
    val item: Item
) {

    private val basePrice: Int = this.quantity * this.item.price
    private val discountFactor: Double = if (basePrice > 1000) 0.95 else 0.98

    val price: Double = this.basePrice * this.discountFactor
}
----
--

=== 배경

함수 내부에서 계산한 값을 다시 참조할 목적으로 임시 변수를 사용
임시 변수는 코드의 중복을 줄이고, 값의 의미를 설명할 수 있어서 유용함
여기서 더 나아가 아예 함수로 만들어 사용하는 편이 좋을 때도 있음

긴 함수에서 한 부분을 별도의 함수로 추출하는 과정에서 임시 변수를 질의 함수로 바꾸는 것이 좋음
추출한 함수와 원래 함수의 경계를 명확히 할 수 있고, 부자연스러운 의존 관계나 부수효과를 찾고 제거하는데 도움이 됨

함수 만들 경우에는, 다른 함수에서도 사용 가능하여, 중복코드를 크게 줄일 수 있음

클래스에서는 추출한 메소드 간의 공유 컨텍스트를 제공하기 때문에, 장점이 있음
다만 최상위 함수로 추출할 경우, 매개변수가 너무 많아져 함수를 사용하는 장점이 줄어듦

임시변수를 질의 함수로 바꾸지 말아야 할 경우도 존재
최초의 값을 할당한 이후에, 값이 변경되지 않아야하는 경우에는 질의 함수로 바꾸지 않는 것이 좋음

** 스냅숏 용도로 쓰인 변수

=== 절차
. 변수가 사용되기 전에 값이 활실히 결정되는지, 변수를 사용할 대마다 계산 로직이 매번 다른 결과를 내지는 않는지 확인한다
. 읽기전용으로 만들 수 있는 변수는 읽기전용으로 만든다
. 테스트한다
. 변수 대입문을 함수로 추출한다
** 변수와 함수가 같은 이름을 가질 수 없다면 함수 이름을 임시로 짓는다. 또한 추출한 함수가 부수효과를 일으키지는 않는지 확인한다. 부수효과가 있다면 질의 함수와 변경 함수 분리하기^11.1절^로 대처한다
. 테스트한다
. 변수 인라인하기^6.4절^로 임시 변수를 제거한다

=== 예시

[open]
.리팩토링 이전
--
[source,kotlin]
----
data class Item (
    val price: Int
)

data class Order(
    val quantity: Int,
    val item: Item
) {
    val price: Double
        get() {
            val basePrice = quantity * item.price
            val discountFactor = if (basePrice > 1000) 0.95 else 0.98

            return basePrice * discountFactor
        }
}
----
--

[open]
.리팩토링 이후
--
[source,kotlin]
----
data class Item (
    val price: Int
)

data class Order(
    val quantity: Int,
    val item: Item
) {

    private val basePrice: Int = this.quantity * this.item.price
    private val discountFactor: Double = if (basePrice > 1000) 0.95 else 0.98

    val price: Double = this.basePrice * this.discountFactor
}
----
--
